services:
  rx:
    build:
      context: .
      dockerfile: RX/Dockerfile
    container_name: uniflow_rx
    volumes:
      - ./received_files:/app/received_files
    networks:
      uniflow_net:
        ipv4_address: 172.20.0.30

  router:
    build:
      context: ./router
      dockerfile: Dockerfile
    container_name: uniflow_router
    command: ["--target-host", "172.20.0.30", "--loss", "0", "--flip", "0", "--misroute", "0"]
    depends_on:
      - rx
    networks:
      uniflow_net:
        ipv4_address: 172.20.0.20

  tx:
    build:
      context: .
      dockerfile: TX/Dockerfile
    container_name: uniflow_tx
    volumes:
      - ./watch_dir:/app/watch_dir
    depends_on:
      - router
    networks:
      uniflow_net:
        ipv4_address: 172.20.0.10

networks:
  uniflow_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24